---
functional:
  - Пользователь должен иметь возможность создать пробную игру без авторизации
  - Пользователь должен иметь возможность зарегистрировать аккаунт
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность авторизоваться на сайте через ранее созданный аккаунт
  - Пользователь должен иметь возможность сделать сквозную авторизацию через GitHub
  - Пользователь должен иметь возможность сделать сквозную авторизацию через Discord
  - Пользователь должен иметь возможность присоединиться к раннее созданной игре
  - Пользователь должен иметь возможность создать игру в ботом со своими настройками
  - Пользователь должен иметь возможность создать игру с другом со своими настройками
  - Пользователь должен иметь возможность создать открытую игру со своими настройками
  - Пользователь должен иметь возможность победить, если первее напишет код, что пройдет тесты
  - Пользователь должен иметь возможность сдаться
  - Пользователь должен иметь возможность следить за идущей игрой других игроков
  - Пользователь должен иметь возможность посмотреть в записи завершенную игру
  - Пользователь должен иметь возможность поменять язык программирования во время игры
  - Пользователь должен иметь возможность видеть редактор кода соперника во время игры
  - Пользователь должен иметь возможность видеть вывод тестов
  - Пользователь должен иметь возможность выбрать язык задачи (английский или русский)
  - Пользователь должен иметь возможность пользоваться чатом для зарегистрированных пользователей
  - Пользователь должен иметь возможность просматривать рейтинг игроков за неделю, месяц и все время
  - Пользователь должен иметь возможность создавать турнир со своими настройками
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - 
